version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - socket_network

  server1:
    build: ./server
    container_name: server1
    environment:
      - PORT=3000
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - socket_network

  server2:
    build: ./server
    container_name: server2
    environment:
      - PORT=3000
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - socket_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
    networks:
      - socket_network

networks:
  socket_network:
    driver: bridge